### ISSUE TITLE
大佬写的文章思路都很清晰

### ISSUE THREAD

**Issue by HeavensHao** [code4wt/mybatis-test#1]
我原来也有阅读源码的习惯,但大多都是看一眼,毕竟这些东西在日常开发中用不到,知道我看了你的一系列讲解后,再回过头来看,我写的真的太差了,阅读完的你的文章,给人的感觉就是思路很清晰,让我对阅读源码这件事也可以提起兴趣了,还配了好多的插图,真的用心了,谢谢你,希望大佬一如既往,我会默默关注你的. 后面我也会按照我的想法,写一些文章

**Comment by code4wt** [comment]
> 我原来也有阅读源码的习惯,但大多都是看一眼,毕竟这些东西在日常开发中用不到,知道我看了你的一系列讲解后,再回过头来看,我写的真的太差了,阅读完的你的文章,给人的感觉就是思路很清晰,让我对阅读源码这件事也可以提起兴趣了,还配了好多的插图,真的用心了,谢谢你,希望大佬一如既往,我会默默关注你的. 后面我也会按照我的想法,写一些文章

感谢阅读。
